# StackSet configuration for multi-account deployment
stack_sets:
  - id: "ec2-stackset"
    name: "EC2 Multi-Account StackSet"
    description: "Deploy EC2 across multiple accounts/regions"
    project_root: "environments/dev"
    runner_image: "public.ecr.aws/spacelift/runner-terragrunt:latest"
    terraform_version: "1.5.0"
    terragrunt_version: "0.50.0"
    branch: "main"
    administrative_stack: true
    target_accounts: ["123456789012", "123456789013", "123456789014"]
    target_regions: ["us-east-1", "us-west-2"]
    labels:
      - "stackset:ec2"
      - "multi-account"

stacks:
  - id: "ec2-dev"
    name: "EC2 Dev Environment"
    description: "Development EC2 instance"
    project_root: "."
    runner_image: "public.ecr.aws/spacelift/runner-terragrunt:latest"
    terraform_version: "1.5.0"
    terragrunt_version: "0.50.0"
    branch: "main"
    autodeploy: true
    before_init:
      - "cd environments/dev"
    labels:
      - "environment:dev"
      - "service:ec2"

  - id: "ec2-stg"
    name: "EC2 Staging Environment"
    description: "Staging EC2 instance"
    project_root: "environments/stg"
    runner_image: "public.ecr.aws/spacelift/runner-terragrunt:latest"
    terraform_version: "1.5.0"
    terragrunt_version: "0.50.0"
    branch: "main"
    autodeploy: false
    depends_on:
      - "ec2-dev"
    labels:
      - "environment:stg"
      - "service:ec2"

  - id: "ec2-prod"
    name: "EC2 Production Environment"
    description: "Production EC2 instance"
    project_root: "environments/prod"
    runner_image: "public.ecr.aws/spacelift/runner-terragrunt:latest"
    terraform_version: "1.5.0"
    terragrunt_version: "0.50.0"
    branch: "main"
    autodeploy: false
    depends_on:
      - "ec2-stg"
    labels:
      - "environment:prod"
      - "service:ec2"
